package sbilms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BuisnessExceptions implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Exception")
   private java.lang.String exception;
   @org.kie.api.definition.type.Label(value = "Exception")
   private java.lang.String reason;

   public BuisnessExceptions()
   {
   }

   public java.lang.String getException()
   {
      return this.exception;
   }

   public void setException(java.lang.String exception)
   {
      this.exception = exception;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public BuisnessExceptions(java.lang.String exception,
         java.lang.String reason)
   {
      this.exception = exception;
      this.reason = reason;
   }

}