package sbilms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Corporate implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "isECR Avaliable")
   private java.lang.Boolean isECRAvaliable;
   @org.kie.api.definition.type.Label(value = "isMoreThanOneECR")
   private java.lang.Integer isMoreThanOneECR;
   @org.kie.api.definition.type.Label(value = "CRAAvaliable")
   private java.lang.Boolean CRAAvaliable;
   @org.kie.api.definition.type.Label(value = "CRACategory")
   private java.lang.String CRACategory;
   @org.kie.api.definition.type.Label(value = "CorporateCreditRating")
   private java.lang.String corporateCreditRating;

   public Corporate()
   {
   }

   public java.lang.Boolean getIsECRAvaliable()
   {
      return this.isECRAvaliable;
   }

   public void setIsECRAvaliable(java.lang.Boolean isECRAvaliable)
   {
      this.isECRAvaliable = isECRAvaliable;
   }

   public java.lang.Integer getIsMoreThanOneECR()
   {
      return this.isMoreThanOneECR;
   }

   public void setIsMoreThanOneECR(java.lang.Integer isMoreThanOneECR)
   {
      this.isMoreThanOneECR = isMoreThanOneECR;
   }

   public java.lang.Boolean getCRAAvaliable()
   {
      return this.CRAAvaliable;
   }

   public void setCRAAvaliable(java.lang.Boolean CRAAvaliable)
   {
      this.CRAAvaliable = CRAAvaliable;
   }

   public java.lang.String getCRACategory()
   {
      return this.CRACategory;
   }

   public void setCRACategory(java.lang.String CRACategory)
   {
      this.CRACategory = CRACategory;
   }

   public java.lang.String getCorporateCreditRating()
   {
      return this.corporateCreditRating;
   }

   public void setCorporateCreditRating(java.lang.String corporateCreditRating)
   {
      this.corporateCreditRating = corporateCreditRating;
   }

   public Corporate(java.lang.Boolean isECRAvaliable,
         java.lang.Integer isMoreThanOneECR, java.lang.Boolean CRAAvaliable,
         java.lang.String CRACategory, java.lang.String corporateCreditRating)
   {
      this.isECRAvaliable = isECRAvaliable;
      this.isMoreThanOneECR = isMoreThanOneECR;
      this.CRAAvaliable = CRAAvaliable;
      this.CRACategory = CRACategory;
      this.corporateCreditRating = corporateCreditRating;
   }

}