package sbilms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XPressProduct implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Loan Scehme")
   private java.lang.String loanScehme;

   @org.kie.api.definition.type.Label("RejectionReason")
   private java.lang.String rejectionReason;

   @org.kie.api.definition.type.Label("RejectedLoanProduct")
   private java.lang.Boolean rejectedLoanProduct;

   @org.kie.api.definition.type.Label("MaxLA")
   private java.lang.Double maxLA;

   @org.kie.api.definition.type.Label("MinLA")
   private java.lang.Double minLA;

   public XPressProduct()
   {
   }

   public java.lang.String getLoanScehme()
   {
      return this.loanScehme;
   }

   public void setLoanScehme(java.lang.String loanScehme)
   {
      this.loanScehme = loanScehme;
   }

   public java.lang.String getRejectionReason()
   {
      return this.rejectionReason;
   }

   public void setRejectionReason(java.lang.String rejectionReason)
   {
      this.rejectionReason = rejectionReason;
   }

   public java.lang.Boolean getRejectedLoanProduct()
   {
      return this.rejectedLoanProduct;
   }

   public void setRejectedLoanProduct(java.lang.Boolean rejectedLoanProduct)
   {
      this.rejectedLoanProduct = rejectedLoanProduct;
   }

   public java.lang.Double getMaxLA()
   {
      return this.maxLA;
   }

   public void setMaxLA(java.lang.Double maxLA)
   {
      this.maxLA = maxLA;
   }

   public java.lang.Double getMinLA()
   {
      return this.minLA;
   }

   public void setMinLA(java.lang.Double minLA)
   {
      this.minLA = minLA;
   }

   public XPressProduct(java.lang.String loanScehme,
         java.lang.String rejectionReason,
         java.lang.Boolean rejectedLoanProduct, java.lang.Double maxLA,
         java.lang.Double minLA)
   {
      this.loanScehme = loanScehme;
      this.rejectionReason = rejectionReason;
      this.rejectedLoanProduct = rejectedLoanProduct;
      this.maxLA = maxLA;
      this.minLA = minLA;
   }

}